package com.example.demo.model;

import javax.persistence.*;

@Table(name = "posdataversion")
public class Posdataversion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posdataversion.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posdataversion.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posdataversion.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posdataversion.dataType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String datatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posdataversion.dataVersion
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String dataversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posdataversion.updateDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posdataversion.id
     *
     * @return the value of posdataversion.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posdataversion.id
     *
     * @param id the value for posdataversion.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posdataversion.storeId
     *
     * @return the value of posdataversion.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posdataversion.storeId
     *
     * @param storeid the value for posdataversion.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posdataversion.posNo
     *
     * @return the value of posdataversion.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posdataversion.posNo
     *
     * @param posno the value for posdataversion.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posdataversion.dataType
     *
     * @return the value of posdataversion.dataType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posdataversion.dataType
     *
     * @param datatype the value for posdataversion.dataType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDatatype(String datatype) {
        this.datatype = datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posdataversion.dataVersion
     *
     * @return the value of posdataversion.dataVersion
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getDataversion() {
        return dataversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posdataversion.dataVersion
     *
     * @param dataversion the value for posdataversion.dataVersion
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDataversion(String dataversion) {
        this.dataversion = dataversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posdataversion.updateDate
     *
     * @return the value of posdataversion.updateDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posdataversion.updateDate
     *
     * @param updatedate the value for posdataversion.updateDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setUpdatedate(String updatedate) {
        this.updatedate = updatedate;
    }
}