package com.example.demo.model;

import javax.persistence.*;

@Table(name = "scanorder")
public class Scanorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scanorder.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scanorder.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scanorder.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scanorder.data
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scanorder.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String systemdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scanorder.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cashiernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scanorder.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String uploadflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scanorder.id
     *
     * @return the value of scanorder.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scanorder.id
     *
     * @param id the value for scanorder.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scanorder.storeId
     *
     * @return the value of scanorder.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scanorder.storeId
     *
     * @param storeid the value for scanorder.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scanorder.posNo
     *
     * @return the value of scanorder.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scanorder.posNo
     *
     * @param posno the value for scanorder.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scanorder.data
     *
     * @return the value of scanorder.data
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scanorder.data
     *
     * @param data the value for scanorder.data
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setData(String data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scanorder.systemDate
     *
     * @return the value of scanorder.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getSystemdate() {
        return systemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scanorder.systemDate
     *
     * @param systemdate the value for scanorder.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setSystemdate(String systemdate) {
        this.systemdate = systemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scanorder.cashierNumber
     *
     * @return the value of scanorder.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCashiernumber() {
        return cashiernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scanorder.cashierNumber
     *
     * @param cashiernumber the value for scanorder.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashiernumber(String cashiernumber) {
        this.cashiernumber = cashiernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scanorder.uploadFlag
     *
     * @return the value of scanorder.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getUploadflag() {
        return uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scanorder.uploadFlag
     *
     * @param uploadflag the value for scanorder.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setUploadflag(String uploadflag) {
        this.uploadflag = uploadflag;
    }
}