package com.example.demo.model;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "shifthead")
public class Shifthead {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.shiftNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer shiftnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer znumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.beginDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String begindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.endDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.beginTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer begintransactionnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.endTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer endtransactionnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String accountdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cashiernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.grossSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal grosssaleamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.discountAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal discountamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.netSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal netsaleamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.tranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer trancount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal returnamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer returncount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.overAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal overamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.paidInAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal paidinamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.paidOutAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal paidoutamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String uploadflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.cashAmount1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal cashamount1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.cashAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal cashamount2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.cashAmount3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal cashamount3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.taxAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal taxamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.daiShouAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal daishouamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.daiShouAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal daishouamount2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.customerCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer customercount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.cashOutAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal cashoutamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.shiftAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal shiftamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shifthead.roundDownAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal rounddownamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.id
     *
     * @return the value of shifthead.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.id
     *
     * @param id the value for shifthead.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.storeId
     *
     * @return the value of shifthead.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.storeId
     *
     * @param storeid the value for shifthead.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.posNo
     *
     * @return the value of shifthead.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.posNo
     *
     * @param posno the value for shifthead.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.shiftNumber
     *
     * @return the value of shifthead.shiftNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getShiftnumber() {
        return shiftnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.shiftNumber
     *
     * @param shiftnumber the value for shifthead.shiftNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setShiftnumber(Integer shiftnumber) {
        this.shiftnumber = shiftnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.zNumber
     *
     * @return the value of shifthead.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getZnumber() {
        return znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.zNumber
     *
     * @param znumber the value for shifthead.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setZnumber(Integer znumber) {
        this.znumber = znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.beginDate
     *
     * @return the value of shifthead.beginDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.beginDate
     *
     * @param begindate the value for shifthead.beginDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setBegindate(String begindate) {
        this.begindate = begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.endDate
     *
     * @return the value of shifthead.endDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.endDate
     *
     * @param enddate the value for shifthead.endDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.beginTransactionNumber
     *
     * @return the value of shifthead.beginTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getBegintransactionnumber() {
        return begintransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.beginTransactionNumber
     *
     * @param begintransactionnumber the value for shifthead.beginTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setBegintransactionnumber(Integer begintransactionnumber) {
        this.begintransactionnumber = begintransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.endTransactionNumber
     *
     * @return the value of shifthead.endTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getEndtransactionnumber() {
        return endtransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.endTransactionNumber
     *
     * @param endtransactionnumber the value for shifthead.endTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setEndtransactionnumber(Integer endtransactionnumber) {
        this.endtransactionnumber = endtransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.accountDate
     *
     * @return the value of shifthead.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getAccountdate() {
        return accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.accountDate
     *
     * @param accountdate the value for shifthead.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setAccountdate(String accountdate) {
        this.accountdate = accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.cashierNumber
     *
     * @return the value of shifthead.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCashiernumber() {
        return cashiernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.cashierNumber
     *
     * @param cashiernumber the value for shifthead.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashiernumber(String cashiernumber) {
        this.cashiernumber = cashiernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.grossSaleAmount
     *
     * @return the value of shifthead.grossSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getGrosssaleamount() {
        return grosssaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.grossSaleAmount
     *
     * @param grosssaleamount the value for shifthead.grossSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setGrosssaleamount(BigDecimal grosssaleamount) {
        this.grosssaleamount = grosssaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.discountAmount
     *
     * @return the value of shifthead.discountAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDiscountamount() {
        return discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.discountAmount
     *
     * @param discountamount the value for shifthead.discountAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDiscountamount(BigDecimal discountamount) {
        this.discountamount = discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.netSaleAmount
     *
     * @return the value of shifthead.netSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getNetsaleamount() {
        return netsaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.netSaleAmount
     *
     * @param netsaleamount the value for shifthead.netSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setNetsaleamount(BigDecimal netsaleamount) {
        this.netsaleamount = netsaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.tranCount
     *
     * @return the value of shifthead.tranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getTrancount() {
        return trancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.tranCount
     *
     * @param trancount the value for shifthead.tranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTrancount(Integer trancount) {
        this.trancount = trancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.returnAmount
     *
     * @return the value of shifthead.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getReturnamount() {
        return returnamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.returnAmount
     *
     * @param returnamount the value for shifthead.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setReturnamount(BigDecimal returnamount) {
        this.returnamount = returnamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.returnCount
     *
     * @return the value of shifthead.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getReturncount() {
        return returncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.returnCount
     *
     * @param returncount the value for shifthead.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setReturncount(Integer returncount) {
        this.returncount = returncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.overAmount
     *
     * @return the value of shifthead.overAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getOveramount() {
        return overamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.overAmount
     *
     * @param overamount the value for shifthead.overAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOveramount(BigDecimal overamount) {
        this.overamount = overamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.paidInAmount
     *
     * @return the value of shifthead.paidInAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPaidinamount() {
        return paidinamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.paidInAmount
     *
     * @param paidinamount the value for shifthead.paidInAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPaidinamount(BigDecimal paidinamount) {
        this.paidinamount = paidinamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.paidOutAmount
     *
     * @return the value of shifthead.paidOutAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPaidoutamount() {
        return paidoutamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.paidOutAmount
     *
     * @param paidoutamount the value for shifthead.paidOutAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPaidoutamount(BigDecimal paidoutamount) {
        this.paidoutamount = paidoutamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.uploadFlag
     *
     * @return the value of shifthead.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getUploadflag() {
        return uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.uploadFlag
     *
     * @param uploadflag the value for shifthead.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setUploadflag(String uploadflag) {
        this.uploadflag = uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.cashAmount1
     *
     * @return the value of shifthead.cashAmount1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getCashamount1() {
        return cashamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.cashAmount1
     *
     * @param cashamount1 the value for shifthead.cashAmount1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashamount1(BigDecimal cashamount1) {
        this.cashamount1 = cashamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.cashAmount2
     *
     * @return the value of shifthead.cashAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getCashamount2() {
        return cashamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.cashAmount2
     *
     * @param cashamount2 the value for shifthead.cashAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashamount2(BigDecimal cashamount2) {
        this.cashamount2 = cashamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.cashAmount3
     *
     * @return the value of shifthead.cashAmount3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getCashamount3() {
        return cashamount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.cashAmount3
     *
     * @param cashamount3 the value for shifthead.cashAmount3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashamount3(BigDecimal cashamount3) {
        this.cashamount3 = cashamount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.taxAmount
     *
     * @return the value of shifthead.taxAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getTaxamount() {
        return taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.taxAmount
     *
     * @param taxamount the value for shifthead.taxAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTaxamount(BigDecimal taxamount) {
        this.taxamount = taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.daiShouAmount
     *
     * @return the value of shifthead.daiShouAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDaishouamount() {
        return daishouamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.daiShouAmount
     *
     * @param daishouamount the value for shifthead.daiShouAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDaishouamount(BigDecimal daishouamount) {
        this.daishouamount = daishouamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.daiShouAmount2
     *
     * @return the value of shifthead.daiShouAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDaishouamount2() {
        return daishouamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.daiShouAmount2
     *
     * @param daishouamount2 the value for shifthead.daiShouAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDaishouamount2(BigDecimal daishouamount2) {
        this.daishouamount2 = daishouamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.customerCount
     *
     * @return the value of shifthead.customerCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getCustomercount() {
        return customercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.customerCount
     *
     * @param customercount the value for shifthead.customerCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCustomercount(Integer customercount) {
        this.customercount = customercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.cashOutAmt
     *
     * @return the value of shifthead.cashOutAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getCashoutamt() {
        return cashoutamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.cashOutAmt
     *
     * @param cashoutamt the value for shifthead.cashOutAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashoutamt(BigDecimal cashoutamt) {
        this.cashoutamt = cashoutamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.shiftAmt
     *
     * @return the value of shifthead.shiftAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getShiftamt() {
        return shiftamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.shiftAmt
     *
     * @param shiftamt the value for shifthead.shiftAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setShiftamt(BigDecimal shiftamt) {
        this.shiftamt = shiftamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shifthead.roundDownAmount
     *
     * @return the value of shifthead.roundDownAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getRounddownamount() {
        return rounddownamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shifthead.roundDownAmount
     *
     * @param rounddownamount the value for shifthead.roundDownAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setRounddownamount(BigDecimal rounddownamount) {
        this.rounddownamount = rounddownamount;
    }
}