package com.example.demo.model;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "tranhead")
public class Tranhead {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer transactionnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.dealType1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String dealtype1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.dealType2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String dealtype2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.dealType3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String dealtype3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String accountdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.shiftNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer shiftnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer znumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String systemdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.cashierNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cashierno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.detailCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer detailcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.saleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal saleamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.payNo1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String payno1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.payAmount1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal payamount1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.payNo2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String payno2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.payAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal payamount2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.payNo3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String payno3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.payAmount3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal payamount3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.payNo4
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String payno4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.payAmount4
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal payamount4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.taxAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal taxamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.changeAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal changeamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.overAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal overamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.roundDownAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal rounddownamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.memberId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String memberid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.grossSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal grosssaleamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.netSaleTotalAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal netsaletotalamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.mmDiscountAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal mmdiscountamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.daishouAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal daishouamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.daishouAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal daishouamount2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.daifuAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal daifuamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.customerId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.customerCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer customercount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.voidTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer voidtransactionnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.voidPosNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer voidposno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.isMemberOffLine
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String ismemberoffline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.takeawayOrderNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String takeawayordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.type
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.platDiscount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal platdiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String uploadflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.verificationMode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String verificationmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.memberId2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String memberid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.offLineEPayCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String offlineepaycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.invoiceno
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String invoiceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.campaignId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String campaignid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.campaignName
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String campaignname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.campaignNum
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String campaignnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.memLevel
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String memlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.totalPoint
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal totalpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.gainedPoint
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer gainedpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.memberZongBai
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String memberzongbai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.wm_type
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer wmType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tranhead.refund_id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String refundId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.id
     *
     * @return the value of tranhead.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.id
     *
     * @param id the value for tranhead.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.storeId
     *
     * @return the value of tranhead.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.storeId
     *
     * @param storeid the value for tranhead.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.posNo
     *
     * @return the value of tranhead.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.posNo
     *
     * @param posno the value for tranhead.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.transactionNumber
     *
     * @return the value of tranhead.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getTransactionnumber() {
        return transactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.transactionNumber
     *
     * @param transactionnumber the value for tranhead.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTransactionnumber(Integer transactionnumber) {
        this.transactionnumber = transactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.dealType1
     *
     * @return the value of tranhead.dealType1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getDealtype1() {
        return dealtype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.dealType1
     *
     * @param dealtype1 the value for tranhead.dealType1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDealtype1(String dealtype1) {
        this.dealtype1 = dealtype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.dealType2
     *
     * @return the value of tranhead.dealType2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getDealtype2() {
        return dealtype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.dealType2
     *
     * @param dealtype2 the value for tranhead.dealType2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDealtype2(String dealtype2) {
        this.dealtype2 = dealtype2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.dealType3
     *
     * @return the value of tranhead.dealType3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getDealtype3() {
        return dealtype3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.dealType3
     *
     * @param dealtype3 the value for tranhead.dealType3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDealtype3(String dealtype3) {
        this.dealtype3 = dealtype3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.accountDate
     *
     * @return the value of tranhead.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getAccountdate() {
        return accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.accountDate
     *
     * @param accountdate the value for tranhead.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setAccountdate(String accountdate) {
        this.accountdate = accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.shiftNumber
     *
     * @return the value of tranhead.shiftNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getShiftnumber() {
        return shiftnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.shiftNumber
     *
     * @param shiftnumber the value for tranhead.shiftNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setShiftnumber(Integer shiftnumber) {
        this.shiftnumber = shiftnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.zNumber
     *
     * @return the value of tranhead.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getZnumber() {
        return znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.zNumber
     *
     * @param znumber the value for tranhead.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setZnumber(Integer znumber) {
        this.znumber = znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.systemDate
     *
     * @return the value of tranhead.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getSystemdate() {
        return systemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.systemDate
     *
     * @param systemdate the value for tranhead.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setSystemdate(String systemdate) {
        this.systemdate = systemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.cashierNo
     *
     * @return the value of tranhead.cashierNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCashierno() {
        return cashierno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.cashierNo
     *
     * @param cashierno the value for tranhead.cashierNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashierno(String cashierno) {
        this.cashierno = cashierno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.detailCount
     *
     * @return the value of tranhead.detailCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getDetailcount() {
        return detailcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.detailCount
     *
     * @param detailcount the value for tranhead.detailCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDetailcount(Integer detailcount) {
        this.detailcount = detailcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.saleAmount
     *
     * @return the value of tranhead.saleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getSaleamount() {
        return saleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.saleAmount
     *
     * @param saleamount the value for tranhead.saleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setSaleamount(BigDecimal saleamount) {
        this.saleamount = saleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.payNo1
     *
     * @return the value of tranhead.payNo1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPayno1() {
        return payno1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.payNo1
     *
     * @param payno1 the value for tranhead.payNo1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayno1(String payno1) {
        this.payno1 = payno1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.payAmount1
     *
     * @return the value of tranhead.payAmount1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPayamount1() {
        return payamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.payAmount1
     *
     * @param payamount1 the value for tranhead.payAmount1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayamount1(BigDecimal payamount1) {
        this.payamount1 = payamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.payNo2
     *
     * @return the value of tranhead.payNo2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPayno2() {
        return payno2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.payNo2
     *
     * @param payno2 the value for tranhead.payNo2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayno2(String payno2) {
        this.payno2 = payno2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.payAmount2
     *
     * @return the value of tranhead.payAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPayamount2() {
        return payamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.payAmount2
     *
     * @param payamount2 the value for tranhead.payAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayamount2(BigDecimal payamount2) {
        this.payamount2 = payamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.payNo3
     *
     * @return the value of tranhead.payNo3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPayno3() {
        return payno3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.payNo3
     *
     * @param payno3 the value for tranhead.payNo3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayno3(String payno3) {
        this.payno3 = payno3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.payAmount3
     *
     * @return the value of tranhead.payAmount3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPayamount3() {
        return payamount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.payAmount3
     *
     * @param payamount3 the value for tranhead.payAmount3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayamount3(BigDecimal payamount3) {
        this.payamount3 = payamount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.payNo4
     *
     * @return the value of tranhead.payNo4
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPayno4() {
        return payno4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.payNo4
     *
     * @param payno4 the value for tranhead.payNo4
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayno4(String payno4) {
        this.payno4 = payno4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.payAmount4
     *
     * @return the value of tranhead.payAmount4
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPayamount4() {
        return payamount4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.payAmount4
     *
     * @param payamount4 the value for tranhead.payAmount4
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayamount4(BigDecimal payamount4) {
        this.payamount4 = payamount4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.taxAmount
     *
     * @return the value of tranhead.taxAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getTaxamount() {
        return taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.taxAmount
     *
     * @param taxamount the value for tranhead.taxAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTaxamount(BigDecimal taxamount) {
        this.taxamount = taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.changeAmount
     *
     * @return the value of tranhead.changeAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getChangeamount() {
        return changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.changeAmount
     *
     * @param changeamount the value for tranhead.changeAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setChangeamount(BigDecimal changeamount) {
        this.changeamount = changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.overAmount
     *
     * @return the value of tranhead.overAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getOveramount() {
        return overamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.overAmount
     *
     * @param overamount the value for tranhead.overAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOveramount(BigDecimal overamount) {
        this.overamount = overamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.roundDownAmount
     *
     * @return the value of tranhead.roundDownAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getRounddownamount() {
        return rounddownamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.roundDownAmount
     *
     * @param rounddownamount the value for tranhead.roundDownAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setRounddownamount(BigDecimal rounddownamount) {
        this.rounddownamount = rounddownamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.memberId
     *
     * @return the value of tranhead.memberId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.memberId
     *
     * @param memberid the value for tranhead.memberId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.grossSaleAmount
     *
     * @return the value of tranhead.grossSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getGrosssaleamount() {
        return grosssaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.grossSaleAmount
     *
     * @param grosssaleamount the value for tranhead.grossSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setGrosssaleamount(BigDecimal grosssaleamount) {
        this.grosssaleamount = grosssaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.netSaleTotalAmount
     *
     * @return the value of tranhead.netSaleTotalAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getNetsaletotalamount() {
        return netsaletotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.netSaleTotalAmount
     *
     * @param netsaletotalamount the value for tranhead.netSaleTotalAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setNetsaletotalamount(BigDecimal netsaletotalamount) {
        this.netsaletotalamount = netsaletotalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.mmDiscountAmount
     *
     * @return the value of tranhead.mmDiscountAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getMmdiscountamount() {
        return mmdiscountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.mmDiscountAmount
     *
     * @param mmdiscountamount the value for tranhead.mmDiscountAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setMmdiscountamount(BigDecimal mmdiscountamount) {
        this.mmdiscountamount = mmdiscountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.daishouAmount
     *
     * @return the value of tranhead.daishouAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDaishouamount() {
        return daishouamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.daishouAmount
     *
     * @param daishouamount the value for tranhead.daishouAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDaishouamount(BigDecimal daishouamount) {
        this.daishouamount = daishouamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.daishouAmount2
     *
     * @return the value of tranhead.daishouAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDaishouamount2() {
        return daishouamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.daishouAmount2
     *
     * @param daishouamount2 the value for tranhead.daishouAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDaishouamount2(BigDecimal daishouamount2) {
        this.daishouamount2 = daishouamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.daifuAmount
     *
     * @return the value of tranhead.daifuAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDaifuamount() {
        return daifuamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.daifuAmount
     *
     * @param daifuamount the value for tranhead.daifuAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDaifuamount(BigDecimal daifuamount) {
        this.daifuamount = daifuamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.customerId
     *
     * @return the value of tranhead.customerId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.customerId
     *
     * @param customerid the value for tranhead.customerId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.customerCount
     *
     * @return the value of tranhead.customerCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getCustomercount() {
        return customercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.customerCount
     *
     * @param customercount the value for tranhead.customerCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCustomercount(Integer customercount) {
        this.customercount = customercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.voidTransactionNumber
     *
     * @return the value of tranhead.voidTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getVoidtransactionnumber() {
        return voidtransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.voidTransactionNumber
     *
     * @param voidtransactionnumber the value for tranhead.voidTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setVoidtransactionnumber(Integer voidtransactionnumber) {
        this.voidtransactionnumber = voidtransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.voidPosNo
     *
     * @return the value of tranhead.voidPosNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getVoidposno() {
        return voidposno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.voidPosNo
     *
     * @param voidposno the value for tranhead.voidPosNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setVoidposno(Integer voidposno) {
        this.voidposno = voidposno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.isMemberOffLine
     *
     * @return the value of tranhead.isMemberOffLine
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getIsmemberoffline() {
        return ismemberoffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.isMemberOffLine
     *
     * @param ismemberoffline the value for tranhead.isMemberOffLine
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setIsmemberoffline(String ismemberoffline) {
        this.ismemberoffline = ismemberoffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.takeawayOrderNumber
     *
     * @return the value of tranhead.takeawayOrderNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTakeawayordernumber() {
        return takeawayordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.takeawayOrderNumber
     *
     * @param takeawayordernumber the value for tranhead.takeawayOrderNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTakeawayordernumber(String takeawayordernumber) {
        this.takeawayordernumber = takeawayordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.type
     *
     * @return the value of tranhead.type
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.type
     *
     * @param type the value for tranhead.type
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.platDiscount
     *
     * @return the value of tranhead.platDiscount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPlatdiscount() {
        return platdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.platDiscount
     *
     * @param platdiscount the value for tranhead.platDiscount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPlatdiscount(BigDecimal platdiscount) {
        this.platdiscount = platdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.uploadFlag
     *
     * @return the value of tranhead.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getUploadflag() {
        return uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.uploadFlag
     *
     * @param uploadflag the value for tranhead.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setUploadflag(String uploadflag) {
        this.uploadflag = uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.verificationMode
     *
     * @return the value of tranhead.verificationMode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getVerificationmode() {
        return verificationmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.verificationMode
     *
     * @param verificationmode the value for tranhead.verificationMode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setVerificationmode(String verificationmode) {
        this.verificationmode = verificationmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.memberId2
     *
     * @return the value of tranhead.memberId2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getMemberid2() {
        return memberid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.memberId2
     *
     * @param memberid2 the value for tranhead.memberId2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setMemberid2(String memberid2) {
        this.memberid2 = memberid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.offLineEPayCode
     *
     * @return the value of tranhead.offLineEPayCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getOfflineepaycode() {
        return offlineepaycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.offLineEPayCode
     *
     * @param offlineepaycode the value for tranhead.offLineEPayCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOfflineepaycode(String offlineepaycode) {
        this.offlineepaycode = offlineepaycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.invoiceno
     *
     * @return the value of tranhead.invoiceno
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getInvoiceno() {
        return invoiceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.invoiceno
     *
     * @param invoiceno the value for tranhead.invoiceno
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setInvoiceno(String invoiceno) {
        this.invoiceno = invoiceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.campaignId
     *
     * @return the value of tranhead.campaignId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCampaignid() {
        return campaignid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.campaignId
     *
     * @param campaignid the value for tranhead.campaignId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCampaignid(String campaignid) {
        this.campaignid = campaignid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.campaignName
     *
     * @return the value of tranhead.campaignName
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCampaignname() {
        return campaignname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.campaignName
     *
     * @param campaignname the value for tranhead.campaignName
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCampaignname(String campaignname) {
        this.campaignname = campaignname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.campaignNum
     *
     * @return the value of tranhead.campaignNum
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCampaignnum() {
        return campaignnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.campaignNum
     *
     * @param campaignnum the value for tranhead.campaignNum
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCampaignnum(String campaignnum) {
        this.campaignnum = campaignnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.memLevel
     *
     * @return the value of tranhead.memLevel
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getMemlevel() {
        return memlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.memLevel
     *
     * @param memlevel the value for tranhead.memLevel
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setMemlevel(String memlevel) {
        this.memlevel = memlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.totalPoint
     *
     * @return the value of tranhead.totalPoint
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getTotalpoint() {
        return totalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.totalPoint
     *
     * @param totalpoint the value for tranhead.totalPoint
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTotalpoint(BigDecimal totalpoint) {
        this.totalpoint = totalpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.gainedPoint
     *
     * @return the value of tranhead.gainedPoint
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getGainedpoint() {
        return gainedpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.gainedPoint
     *
     * @param gainedpoint the value for tranhead.gainedPoint
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setGainedpoint(Integer gainedpoint) {
        this.gainedpoint = gainedpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.memberZongBai
     *
     * @return the value of tranhead.memberZongBai
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getMemberzongbai() {
        return memberzongbai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.memberZongBai
     *
     * @param memberzongbai the value for tranhead.memberZongBai
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setMemberzongbai(String memberzongbai) {
        this.memberzongbai = memberzongbai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.wm_type
     *
     * @return the value of tranhead.wm_type
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getWmType() {
        return wmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.wm_type
     *
     * @param wmType the value for tranhead.wm_type
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setWmType(Integer wmType) {
        this.wmType = wmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranhead.refund_id
     *
     * @return the value of tranhead.refund_id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranhead.refund_id
     *
     * @param refundId the value for tranhead.refund_id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }
}