package com.example.demo.model;

import javax.persistence.*;

@Table(name = "whtopupresponse")
public class Whtopupresponse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer transactionnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.statusCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String statuscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.tranRunningWaterNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String tranrunningwaternumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.wuHanTongRunningWaterNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String wuhantongrunningwaternumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.tranType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String trantype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.tranMoney
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String tranmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.tranDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String trandate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.systemTerminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String systemterminalnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.psamCardNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String psamcardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.terminalTranSerialNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String terminaltranserialnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.webSiteEncoding
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String websiteencoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.publisherMainEncoding
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String publishermainencoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.publisherChildEncoding
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String publisherchildencoding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.logicalCardNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String logicalcardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.physicsNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String physicsnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.yinKeNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String yinkenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.cardMainType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cardmaintype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.cardChildType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cardchildtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.onlineCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String onlinecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.offlineCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String offlinecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.topUpBeforeBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String topupbeforebalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.topUpAfterBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String topupafterbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.tac
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String tac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.cardBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cardbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whtopupresponse.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String uploadflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.id
     *
     * @return the value of whtopupresponse.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.id
     *
     * @param id the value for whtopupresponse.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.storeId
     *
     * @return the value of whtopupresponse.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.storeId
     *
     * @param storeid the value for whtopupresponse.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.posNo
     *
     * @return the value of whtopupresponse.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.posNo
     *
     * @param posno the value for whtopupresponse.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.transactionNumber
     *
     * @return the value of whtopupresponse.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getTransactionnumber() {
        return transactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.transactionNumber
     *
     * @param transactionnumber the value for whtopupresponse.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTransactionnumber(Integer transactionnumber) {
        this.transactionnumber = transactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.statusCode
     *
     * @return the value of whtopupresponse.statusCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStatuscode() {
        return statuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.statusCode
     *
     * @param statuscode the value for whtopupresponse.statusCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStatuscode(String statuscode) {
        this.statuscode = statuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.tranRunningWaterNumber
     *
     * @return the value of whtopupresponse.tranRunningWaterNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTranrunningwaternumber() {
        return tranrunningwaternumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.tranRunningWaterNumber
     *
     * @param tranrunningwaternumber the value for whtopupresponse.tranRunningWaterNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTranrunningwaternumber(String tranrunningwaternumber) {
        this.tranrunningwaternumber = tranrunningwaternumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.wuHanTongRunningWaterNumber
     *
     * @return the value of whtopupresponse.wuHanTongRunningWaterNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getWuhantongrunningwaternumber() {
        return wuhantongrunningwaternumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.wuHanTongRunningWaterNumber
     *
     * @param wuhantongrunningwaternumber the value for whtopupresponse.wuHanTongRunningWaterNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setWuhantongrunningwaternumber(String wuhantongrunningwaternumber) {
        this.wuhantongrunningwaternumber = wuhantongrunningwaternumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.tranType
     *
     * @return the value of whtopupresponse.tranType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTrantype() {
        return trantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.tranType
     *
     * @param trantype the value for whtopupresponse.tranType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTrantype(String trantype) {
        this.trantype = trantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.tranMoney
     *
     * @return the value of whtopupresponse.tranMoney
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTranmoney() {
        return tranmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.tranMoney
     *
     * @param tranmoney the value for whtopupresponse.tranMoney
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTranmoney(String tranmoney) {
        this.tranmoney = tranmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.tranDate
     *
     * @return the value of whtopupresponse.tranDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTrandate() {
        return trandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.tranDate
     *
     * @param trandate the value for whtopupresponse.tranDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTrandate(String trandate) {
        this.trandate = trandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.systemTerminalNumber
     *
     * @return the value of whtopupresponse.systemTerminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getSystemterminalnumber() {
        return systemterminalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.systemTerminalNumber
     *
     * @param systemterminalnumber the value for whtopupresponse.systemTerminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setSystemterminalnumber(String systemterminalnumber) {
        this.systemterminalnumber = systemterminalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.psamCardNumber
     *
     * @return the value of whtopupresponse.psamCardNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPsamcardnumber() {
        return psamcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.psamCardNumber
     *
     * @param psamcardnumber the value for whtopupresponse.psamCardNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPsamcardnumber(String psamcardnumber) {
        this.psamcardnumber = psamcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.terminalTranSerialNumber
     *
     * @return the value of whtopupresponse.terminalTranSerialNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTerminaltranserialnumber() {
        return terminaltranserialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.terminalTranSerialNumber
     *
     * @param terminaltranserialnumber the value for whtopupresponse.terminalTranSerialNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTerminaltranserialnumber(String terminaltranserialnumber) {
        this.terminaltranserialnumber = terminaltranserialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.webSiteEncoding
     *
     * @return the value of whtopupresponse.webSiteEncoding
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getWebsiteencoding() {
        return websiteencoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.webSiteEncoding
     *
     * @param websiteencoding the value for whtopupresponse.webSiteEncoding
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setWebsiteencoding(String websiteencoding) {
        this.websiteencoding = websiteencoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.publisherMainEncoding
     *
     * @return the value of whtopupresponse.publisherMainEncoding
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPublishermainencoding() {
        return publishermainencoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.publisherMainEncoding
     *
     * @param publishermainencoding the value for whtopupresponse.publisherMainEncoding
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPublishermainencoding(String publishermainencoding) {
        this.publishermainencoding = publishermainencoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.publisherChildEncoding
     *
     * @return the value of whtopupresponse.publisherChildEncoding
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPublisherchildencoding() {
        return publisherchildencoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.publisherChildEncoding
     *
     * @param publisherchildencoding the value for whtopupresponse.publisherChildEncoding
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPublisherchildencoding(String publisherchildencoding) {
        this.publisherchildencoding = publisherchildencoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.logicalCardNumber
     *
     * @return the value of whtopupresponse.logicalCardNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getLogicalcardnumber() {
        return logicalcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.logicalCardNumber
     *
     * @param logicalcardnumber the value for whtopupresponse.logicalCardNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setLogicalcardnumber(String logicalcardnumber) {
        this.logicalcardnumber = logicalcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.physicsNumber
     *
     * @return the value of whtopupresponse.physicsNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPhysicsnumber() {
        return physicsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.physicsNumber
     *
     * @param physicsnumber the value for whtopupresponse.physicsNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPhysicsnumber(String physicsnumber) {
        this.physicsnumber = physicsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.yinKeNumber
     *
     * @return the value of whtopupresponse.yinKeNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getYinkenumber() {
        return yinkenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.yinKeNumber
     *
     * @param yinkenumber the value for whtopupresponse.yinKeNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setYinkenumber(String yinkenumber) {
        this.yinkenumber = yinkenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.cardMainType
     *
     * @return the value of whtopupresponse.cardMainType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCardmaintype() {
        return cardmaintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.cardMainType
     *
     * @param cardmaintype the value for whtopupresponse.cardMainType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCardmaintype(String cardmaintype) {
        this.cardmaintype = cardmaintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.cardChildType
     *
     * @return the value of whtopupresponse.cardChildType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCardchildtype() {
        return cardchildtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.cardChildType
     *
     * @param cardchildtype the value for whtopupresponse.cardChildType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCardchildtype(String cardchildtype) {
        this.cardchildtype = cardchildtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.onlineCount
     *
     * @return the value of whtopupresponse.onlineCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getOnlinecount() {
        return onlinecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.onlineCount
     *
     * @param onlinecount the value for whtopupresponse.onlineCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOnlinecount(String onlinecount) {
        this.onlinecount = onlinecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.offlineCount
     *
     * @return the value of whtopupresponse.offlineCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getOfflinecount() {
        return offlinecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.offlineCount
     *
     * @param offlinecount the value for whtopupresponse.offlineCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOfflinecount(String offlinecount) {
        this.offlinecount = offlinecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.topUpBeforeBalance
     *
     * @return the value of whtopupresponse.topUpBeforeBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTopupbeforebalance() {
        return topupbeforebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.topUpBeforeBalance
     *
     * @param topupbeforebalance the value for whtopupresponse.topUpBeforeBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTopupbeforebalance(String topupbeforebalance) {
        this.topupbeforebalance = topupbeforebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.topUpAfterBalance
     *
     * @return the value of whtopupresponse.topUpAfterBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTopupafterbalance() {
        return topupafterbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.topUpAfterBalance
     *
     * @param topupafterbalance the value for whtopupresponse.topUpAfterBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTopupafterbalance(String topupafterbalance) {
        this.topupafterbalance = topupafterbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.tac
     *
     * @return the value of whtopupresponse.tac
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTac() {
        return tac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.tac
     *
     * @param tac the value for whtopupresponse.tac
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTac(String tac) {
        this.tac = tac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.cardBalance
     *
     * @return the value of whtopupresponse.cardBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCardbalance() {
        return cardbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.cardBalance
     *
     * @param cardbalance the value for whtopupresponse.cardBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCardbalance(String cardbalance) {
        this.cardbalance = cardbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whtopupresponse.uploadFlag
     *
     * @return the value of whtopupresponse.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getUploadflag() {
        return uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whtopupresponse.uploadFlag
     *
     * @param uploadflag the value for whtopupresponse.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setUploadflag(String uploadflag) {
        this.uploadflag = uploadflag;
    }
}