package com.example.demo.model;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "zhead")
public class Zhead {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer znumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.beginDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String begindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.endDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.beginTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer begintransactionnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.endTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer endtransactionnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String accountdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cashiernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.grossSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal grosssaleamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.discountAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal discountamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.netSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal netsaleamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.tranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer trancount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal returnamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer returncount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.overAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal overamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.paidInAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal paidinamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.paidOutAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal paidoutamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String uploadflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.cashAmount1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal cashamount1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.cashAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal cashamount2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.cashAmount3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal cashamount3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.taxAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal taxamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.daiShouAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal daishouamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.daiShouAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal daishouamount2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.customerCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer customercount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.cashOutAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal cashoutamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.shiftAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal shiftamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhead.roundDownAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal rounddownamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.id
     *
     * @return the value of zhead.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.id
     *
     * @param id the value for zhead.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.storeId
     *
     * @return the value of zhead.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.storeId
     *
     * @param storeid the value for zhead.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.posNo
     *
     * @return the value of zhead.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.posNo
     *
     * @param posno the value for zhead.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.zNumber
     *
     * @return the value of zhead.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getZnumber() {
        return znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.zNumber
     *
     * @param znumber the value for zhead.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setZnumber(Integer znumber) {
        this.znumber = znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.beginDate
     *
     * @return the value of zhead.beginDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.beginDate
     *
     * @param begindate the value for zhead.beginDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setBegindate(String begindate) {
        this.begindate = begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.endDate
     *
     * @return the value of zhead.endDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.endDate
     *
     * @param enddate the value for zhead.endDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setEnddate(String enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.beginTransactionNumber
     *
     * @return the value of zhead.beginTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getBegintransactionnumber() {
        return begintransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.beginTransactionNumber
     *
     * @param begintransactionnumber the value for zhead.beginTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setBegintransactionnumber(Integer begintransactionnumber) {
        this.begintransactionnumber = begintransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.endTransactionNumber
     *
     * @return the value of zhead.endTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getEndtransactionnumber() {
        return endtransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.endTransactionNumber
     *
     * @param endtransactionnumber the value for zhead.endTransactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setEndtransactionnumber(Integer endtransactionnumber) {
        this.endtransactionnumber = endtransactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.accountDate
     *
     * @return the value of zhead.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getAccountdate() {
        return accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.accountDate
     *
     * @param accountdate the value for zhead.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setAccountdate(String accountdate) {
        this.accountdate = accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.cashierNumber
     *
     * @return the value of zhead.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCashiernumber() {
        return cashiernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.cashierNumber
     *
     * @param cashiernumber the value for zhead.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashiernumber(String cashiernumber) {
        this.cashiernumber = cashiernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.grossSaleAmount
     *
     * @return the value of zhead.grossSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getGrosssaleamount() {
        return grosssaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.grossSaleAmount
     *
     * @param grosssaleamount the value for zhead.grossSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setGrosssaleamount(BigDecimal grosssaleamount) {
        this.grosssaleamount = grosssaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.discountAmount
     *
     * @return the value of zhead.discountAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDiscountamount() {
        return discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.discountAmount
     *
     * @param discountamount the value for zhead.discountAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDiscountamount(BigDecimal discountamount) {
        this.discountamount = discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.netSaleAmount
     *
     * @return the value of zhead.netSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getNetsaleamount() {
        return netsaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.netSaleAmount
     *
     * @param netsaleamount the value for zhead.netSaleAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setNetsaleamount(BigDecimal netsaleamount) {
        this.netsaleamount = netsaleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.tranCount
     *
     * @return the value of zhead.tranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getTrancount() {
        return trancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.tranCount
     *
     * @param trancount the value for zhead.tranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTrancount(Integer trancount) {
        this.trancount = trancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.returnAmount
     *
     * @return the value of zhead.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getReturnamount() {
        return returnamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.returnAmount
     *
     * @param returnamount the value for zhead.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setReturnamount(BigDecimal returnamount) {
        this.returnamount = returnamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.returnCount
     *
     * @return the value of zhead.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getReturncount() {
        return returncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.returnCount
     *
     * @param returncount the value for zhead.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setReturncount(Integer returncount) {
        this.returncount = returncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.overAmount
     *
     * @return the value of zhead.overAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getOveramount() {
        return overamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.overAmount
     *
     * @param overamount the value for zhead.overAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOveramount(BigDecimal overamount) {
        this.overamount = overamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.paidInAmount
     *
     * @return the value of zhead.paidInAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPaidinamount() {
        return paidinamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.paidInAmount
     *
     * @param paidinamount the value for zhead.paidInAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPaidinamount(BigDecimal paidinamount) {
        this.paidinamount = paidinamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.paidOutAmount
     *
     * @return the value of zhead.paidOutAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPaidoutamount() {
        return paidoutamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.paidOutAmount
     *
     * @param paidoutamount the value for zhead.paidOutAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPaidoutamount(BigDecimal paidoutamount) {
        this.paidoutamount = paidoutamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.uploadFlag
     *
     * @return the value of zhead.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getUploadflag() {
        return uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.uploadFlag
     *
     * @param uploadflag the value for zhead.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setUploadflag(String uploadflag) {
        this.uploadflag = uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.cashAmount1
     *
     * @return the value of zhead.cashAmount1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getCashamount1() {
        return cashamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.cashAmount1
     *
     * @param cashamount1 the value for zhead.cashAmount1
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashamount1(BigDecimal cashamount1) {
        this.cashamount1 = cashamount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.cashAmount2
     *
     * @return the value of zhead.cashAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getCashamount2() {
        return cashamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.cashAmount2
     *
     * @param cashamount2 the value for zhead.cashAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashamount2(BigDecimal cashamount2) {
        this.cashamount2 = cashamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.cashAmount3
     *
     * @return the value of zhead.cashAmount3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getCashamount3() {
        return cashamount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.cashAmount3
     *
     * @param cashamount3 the value for zhead.cashAmount3
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashamount3(BigDecimal cashamount3) {
        this.cashamount3 = cashamount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.taxAmount
     *
     * @return the value of zhead.taxAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getTaxamount() {
        return taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.taxAmount
     *
     * @param taxamount the value for zhead.taxAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTaxamount(BigDecimal taxamount) {
        this.taxamount = taxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.daiShouAmount
     *
     * @return the value of zhead.daiShouAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDaishouamount() {
        return daishouamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.daiShouAmount
     *
     * @param daishouamount the value for zhead.daiShouAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDaishouamount(BigDecimal daishouamount) {
        this.daishouamount = daishouamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.daiShouAmount2
     *
     * @return the value of zhead.daiShouAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDaishouamount2() {
        return daishouamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.daiShouAmount2
     *
     * @param daishouamount2 the value for zhead.daiShouAmount2
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDaishouamount2(BigDecimal daishouamount2) {
        this.daishouamount2 = daishouamount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.customerCount
     *
     * @return the value of zhead.customerCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getCustomercount() {
        return customercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.customerCount
     *
     * @param customercount the value for zhead.customerCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCustomercount(Integer customercount) {
        this.customercount = customercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.cashOutAmt
     *
     * @return the value of zhead.cashOutAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getCashoutamt() {
        return cashoutamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.cashOutAmt
     *
     * @param cashoutamt the value for zhead.cashOutAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashoutamt(BigDecimal cashoutamt) {
        this.cashoutamt = cashoutamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.shiftAmt
     *
     * @return the value of zhead.shiftAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getShiftamt() {
        return shiftamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.shiftAmt
     *
     * @param shiftamt the value for zhead.shiftAmt
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setShiftamt(BigDecimal shiftamt) {
        this.shiftamt = shiftamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhead.roundDownAmount
     *
     * @return the value of zhead.roundDownAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getRounddownamount() {
        return rounddownamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhead.roundDownAmount
     *
     * @param rounddownamount the value for zhead.roundDownAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setRounddownamount(BigDecimal rounddownamount) {
        this.rounddownamount = rounddownamount;
    }
}