package com.example.demo.model;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "ff_save")
public class FfSave {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ff_save.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ff_save.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ff_save.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ff_save.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String systemdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ff_save.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cashiernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ff_save.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String uploadflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ff_save.pluNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String pluno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ff_save.itemNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String itemno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ff_save.qty
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ff_save.id
     *
     * @return the value of ff_save.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ff_save.id
     *
     * @param id the value for ff_save.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ff_save.storeId
     *
     * @return the value of ff_save.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ff_save.storeId
     *
     * @param storeid the value for ff_save.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ff_save.posNo
     *
     * @return the value of ff_save.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ff_save.posNo
     *
     * @param posno the value for ff_save.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ff_save.systemDate
     *
     * @return the value of ff_save.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getSystemdate() {
        return systemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ff_save.systemDate
     *
     * @param systemdate the value for ff_save.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setSystemdate(String systemdate) {
        this.systemdate = systemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ff_save.cashierNumber
     *
     * @return the value of ff_save.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCashiernumber() {
        return cashiernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ff_save.cashierNumber
     *
     * @param cashiernumber the value for ff_save.cashierNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCashiernumber(String cashiernumber) {
        this.cashiernumber = cashiernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ff_save.uploadFlag
     *
     * @return the value of ff_save.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getUploadflag() {
        return uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ff_save.uploadFlag
     *
     * @param uploadflag the value for ff_save.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setUploadflag(String uploadflag) {
        this.uploadflag = uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ff_save.pluNo
     *
     * @return the value of ff_save.pluNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPluno() {
        return pluno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ff_save.pluNo
     *
     * @param pluno the value for ff_save.pluNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPluno(String pluno) {
        this.pluno = pluno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ff_save.itemNo
     *
     * @return the value of ff_save.itemNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getItemno() {
        return itemno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ff_save.itemNo
     *
     * @param itemno the value for ff_save.itemNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setItemno(String itemno) {
        this.itemno = itemno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ff_save.qty
     *
     * @return the value of ff_save.qty
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ff_save.qty
     *
     * @param qty the value for ff_save.qty
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }
}