package com.example.demo.model;

import javax.persistence.*;

@Table(name = "kargocard_sale")
public class KargocardSale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer transactionnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.seq
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.name
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.cardnumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.outid
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String outid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.validdate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String validdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.status
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String systemdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.terminalId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String terminalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.outTradeNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String outtradeno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.tradeNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String tradeno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.pluPrice
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String pluprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kargocard_sale.pluNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String pluno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.storeId
     *
     * @return the value of kargocard_sale.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.storeId
     *
     * @param storeid the value for kargocard_sale.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.posNo
     *
     * @return the value of kargocard_sale.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.posNo
     *
     * @param posno the value for kargocard_sale.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.transactionNumber
     *
     * @return the value of kargocard_sale.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getTransactionnumber() {
        return transactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.transactionNumber
     *
     * @param transactionnumber the value for kargocard_sale.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTransactionnumber(Integer transactionnumber) {
        this.transactionnumber = transactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.seq
     *
     * @return the value of kargocard_sale.seq
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.seq
     *
     * @param seq the value for kargocard_sale.seq
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.name
     *
     * @return the value of kargocard_sale.name
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.name
     *
     * @param name the value for kargocard_sale.name
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.cardnumber
     *
     * @return the value of kargocard_sale.cardnumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCardnumber() {
        return cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.cardnumber
     *
     * @param cardnumber the value for kargocard_sale.cardnumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.outid
     *
     * @return the value of kargocard_sale.outid
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getOutid() {
        return outid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.outid
     *
     * @param outid the value for kargocard_sale.outid
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOutid(String outid) {
        this.outid = outid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.validdate
     *
     * @return the value of kargocard_sale.validdate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getValiddate() {
        return validdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.validdate
     *
     * @param validdate the value for kargocard_sale.validdate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setValiddate(String validdate) {
        this.validdate = validdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.status
     *
     * @return the value of kargocard_sale.status
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.status
     *
     * @param status the value for kargocard_sale.status
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.systemDate
     *
     * @return the value of kargocard_sale.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getSystemdate() {
        return systemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.systemDate
     *
     * @param systemdate the value for kargocard_sale.systemDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setSystemdate(String systemdate) {
        this.systemdate = systemdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.terminalId
     *
     * @return the value of kargocard_sale.terminalId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTerminalid() {
        return terminalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.terminalId
     *
     * @param terminalid the value for kargocard_sale.terminalId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.outTradeNo
     *
     * @return the value of kargocard_sale.outTradeNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getOuttradeno() {
        return outtradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.outTradeNo
     *
     * @param outtradeno the value for kargocard_sale.outTradeNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOuttradeno(String outtradeno) {
        this.outtradeno = outtradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.tradeNo
     *
     * @return the value of kargocard_sale.tradeNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTradeno() {
        return tradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.tradeNo
     *
     * @param tradeno the value for kargocard_sale.tradeNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTradeno(String tradeno) {
        this.tradeno = tradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.pluPrice
     *
     * @return the value of kargocard_sale.pluPrice
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPluprice() {
        return pluprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.pluPrice
     *
     * @param pluprice the value for kargocard_sale.pluPrice
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPluprice(String pluprice) {
        this.pluprice = pluprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kargocard_sale.pluNo
     *
     * @return the value of kargocard_sale.pluNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPluno() {
        return pluno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kargocard_sale.pluNo
     *
     * @param pluno the value for kargocard_sale.pluNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPluno(String pluno) {
        this.pluno = pluno;
    }
}