package com.example.demo.model;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "outsale_discount")
public class OutsaleDiscount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.order_id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.seq
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.discount_code
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String discountCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.discount_name
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String discountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.discount_type
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.discount_fee
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal discountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.discount_wm_fee
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal discountWmFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.discount_mt_fee
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal discountMtFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.remark
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outsale_discount.extras
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String extras;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.order_id
     *
     * @return the value of outsale_discount.order_id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.order_id
     *
     * @param orderId the value for outsale_discount.order_id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.seq
     *
     * @return the value of outsale_discount.seq
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.seq
     *
     * @param seq the value for outsale_discount.seq
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.discount_code
     *
     * @return the value of outsale_discount.discount_code
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getDiscountCode() {
        return discountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.discount_code
     *
     * @param discountCode the value for outsale_discount.discount_code
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDiscountCode(String discountCode) {
        this.discountCode = discountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.discount_name
     *
     * @return the value of outsale_discount.discount_name
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getDiscountName() {
        return discountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.discount_name
     *
     * @param discountName the value for outsale_discount.discount_name
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDiscountName(String discountName) {
        this.discountName = discountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.discount_type
     *
     * @return the value of outsale_discount.discount_type
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.discount_type
     *
     * @param discountType the value for outsale_discount.discount_type
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDiscountType(String discountType) {
        this.discountType = discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.discount_fee
     *
     * @return the value of outsale_discount.discount_fee
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.discount_fee
     *
     * @param discountFee the value for outsale_discount.discount_fee
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDiscountFee(BigDecimal discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.discount_wm_fee
     *
     * @return the value of outsale_discount.discount_wm_fee
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDiscountWmFee() {
        return discountWmFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.discount_wm_fee
     *
     * @param discountWmFee the value for outsale_discount.discount_wm_fee
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDiscountWmFee(BigDecimal discountWmFee) {
        this.discountWmFee = discountWmFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.discount_mt_fee
     *
     * @return the value of outsale_discount.discount_mt_fee
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getDiscountMtFee() {
        return discountMtFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.discount_mt_fee
     *
     * @param discountMtFee the value for outsale_discount.discount_mt_fee
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setDiscountMtFee(BigDecimal discountMtFee) {
        this.discountMtFee = discountMtFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.remark
     *
     * @return the value of outsale_discount.remark
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.remark
     *
     * @param remark the value for outsale_discount.remark
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outsale_discount.extras
     *
     * @return the value of outsale_discount.extras
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getExtras() {
        return extras;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outsale_discount.extras
     *
     * @param extras the value for outsale_discount.extras
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setExtras(String extras) {
        this.extras = extras;
    }
}