package com.example.demo.model;

import javax.persistence.*;

@Table(name = "pos_property")
public class PosProperty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_property.name
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_property.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos_property.value
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_property.name
     *
     * @return the value of pos_property.name
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_property.name
     *
     * @param name the value for pos_property.name
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_property.posNo
     *
     * @return the value of pos_property.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_property.posNo
     *
     * @param posno the value for pos_property.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos_property.value
     *
     * @return the value of pos_property.value
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos_property.value
     *
     * @param value the value for pos_property.value
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setValue(String value) {
        this.value = value;
    }
}