package com.example.demo.model;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "shiftpayment")
public class Shiftpayment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.shiftNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer shiftnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer znumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.payNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String payno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.payAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal payamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.payCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer paycount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.payCat
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String paycat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal returnamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiftpayment.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer returncount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.id
     *
     * @return the value of shiftpayment.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.id
     *
     * @param id the value for shiftpayment.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.storeId
     *
     * @return the value of shiftpayment.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.storeId
     *
     * @param storeid the value for shiftpayment.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.posNo
     *
     * @return the value of shiftpayment.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.posNo
     *
     * @param posno the value for shiftpayment.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.shiftNumber
     *
     * @return the value of shiftpayment.shiftNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getShiftnumber() {
        return shiftnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.shiftNumber
     *
     * @param shiftnumber the value for shiftpayment.shiftNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setShiftnumber(Integer shiftnumber) {
        this.shiftnumber = shiftnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.zNumber
     *
     * @return the value of shiftpayment.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getZnumber() {
        return znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.zNumber
     *
     * @param znumber the value for shiftpayment.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setZnumber(Integer znumber) {
        this.znumber = znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.payNo
     *
     * @return the value of shiftpayment.payNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPayno() {
        return payno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.payNo
     *
     * @param payno the value for shiftpayment.payNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayno(String payno) {
        this.payno = payno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.payAmount
     *
     * @return the value of shiftpayment.payAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.payAmount
     *
     * @param payamount the value for shiftpayment.payAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayamount(BigDecimal payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.payCount
     *
     * @return the value of shiftpayment.payCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPaycount() {
        return paycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.payCount
     *
     * @param paycount the value for shiftpayment.payCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPaycount(Integer paycount) {
        this.paycount = paycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.payCat
     *
     * @return the value of shiftpayment.payCat
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPaycat() {
        return paycat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.payCat
     *
     * @param paycat the value for shiftpayment.payCat
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPaycat(String paycat) {
        this.paycat = paycat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.returnAmount
     *
     * @return the value of shiftpayment.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getReturnamount() {
        return returnamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.returnAmount
     *
     * @param returnamount the value for shiftpayment.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setReturnamount(BigDecimal returnamount) {
        this.returnamount = returnamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiftpayment.returnCount
     *
     * @return the value of shiftpayment.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getReturncount() {
        return returncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiftpayment.returnCount
     *
     * @param returncount the value for shiftpayment.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setReturncount(Integer returncount) {
        this.returncount = returncount;
    }
}