package com.example.demo.model;

import javax.persistence.*;

@Table(name = "whexpenseresponse")
public class Whexpenseresponse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer transactionnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.statusCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String statuscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.tranRunningWater
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String tranrunningwater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.terminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String terminalnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.terminalFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String terminalflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.tranDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String trandate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.terminalRunningWaterNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String terminalrunningwaternumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.logicalCardNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String logicalcardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.physicsNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String physicsnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.cardMainType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cardmaintype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.cardChildType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String cardchildtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.lastTimeTerminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String lasttimeterminalnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.lastTimeDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String lasttimedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.tranMoney
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String tranmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.thisTimeBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String thistimebalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.tranType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String trantype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.thisTimeTerminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String thistimeterminalnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.thisTimeDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String thistimedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.onlineTranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String onlinetrancount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.offlineTranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String offlinetrancount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.tranAuthenticationCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String tranauthenticationcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.testCardFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String testcardflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.reservedField
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String reservedfield;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column whexpenseresponse.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String uploadflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.id
     *
     * @return the value of whexpenseresponse.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.id
     *
     * @param id the value for whexpenseresponse.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.storeId
     *
     * @return the value of whexpenseresponse.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.storeId
     *
     * @param storeid the value for whexpenseresponse.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.posNo
     *
     * @return the value of whexpenseresponse.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.posNo
     *
     * @param posno the value for whexpenseresponse.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.transactionNumber
     *
     * @return the value of whexpenseresponse.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getTransactionnumber() {
        return transactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.transactionNumber
     *
     * @param transactionnumber the value for whexpenseresponse.transactionNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTransactionnumber(Integer transactionnumber) {
        this.transactionnumber = transactionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.statusCode
     *
     * @return the value of whexpenseresponse.statusCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStatuscode() {
        return statuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.statusCode
     *
     * @param statuscode the value for whexpenseresponse.statusCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStatuscode(String statuscode) {
        this.statuscode = statuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.tranRunningWater
     *
     * @return the value of whexpenseresponse.tranRunningWater
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTranrunningwater() {
        return tranrunningwater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.tranRunningWater
     *
     * @param tranrunningwater the value for whexpenseresponse.tranRunningWater
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTranrunningwater(String tranrunningwater) {
        this.tranrunningwater = tranrunningwater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.terminalNumber
     *
     * @return the value of whexpenseresponse.terminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTerminalnumber() {
        return terminalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.terminalNumber
     *
     * @param terminalnumber the value for whexpenseresponse.terminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTerminalnumber(String terminalnumber) {
        this.terminalnumber = terminalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.terminalFlag
     *
     * @return the value of whexpenseresponse.terminalFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTerminalflag() {
        return terminalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.terminalFlag
     *
     * @param terminalflag the value for whexpenseresponse.terminalFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTerminalflag(String terminalflag) {
        this.terminalflag = terminalflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.tranDate
     *
     * @return the value of whexpenseresponse.tranDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTrandate() {
        return trandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.tranDate
     *
     * @param trandate the value for whexpenseresponse.tranDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTrandate(String trandate) {
        this.trandate = trandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.terminalRunningWaterNumber
     *
     * @return the value of whexpenseresponse.terminalRunningWaterNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTerminalrunningwaternumber() {
        return terminalrunningwaternumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.terminalRunningWaterNumber
     *
     * @param terminalrunningwaternumber the value for whexpenseresponse.terminalRunningWaterNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTerminalrunningwaternumber(String terminalrunningwaternumber) {
        this.terminalrunningwaternumber = terminalrunningwaternumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.logicalCardNumber
     *
     * @return the value of whexpenseresponse.logicalCardNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getLogicalcardnumber() {
        return logicalcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.logicalCardNumber
     *
     * @param logicalcardnumber the value for whexpenseresponse.logicalCardNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setLogicalcardnumber(String logicalcardnumber) {
        this.logicalcardnumber = logicalcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.physicsNumber
     *
     * @return the value of whexpenseresponse.physicsNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPhysicsnumber() {
        return physicsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.physicsNumber
     *
     * @param physicsnumber the value for whexpenseresponse.physicsNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPhysicsnumber(String physicsnumber) {
        this.physicsnumber = physicsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.cardMainType
     *
     * @return the value of whexpenseresponse.cardMainType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCardmaintype() {
        return cardmaintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.cardMainType
     *
     * @param cardmaintype the value for whexpenseresponse.cardMainType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCardmaintype(String cardmaintype) {
        this.cardmaintype = cardmaintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.cardChildType
     *
     * @return the value of whexpenseresponse.cardChildType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getCardchildtype() {
        return cardchildtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.cardChildType
     *
     * @param cardchildtype the value for whexpenseresponse.cardChildType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setCardchildtype(String cardchildtype) {
        this.cardchildtype = cardchildtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.lastTimeTerminalNumber
     *
     * @return the value of whexpenseresponse.lastTimeTerminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getLasttimeterminalnumber() {
        return lasttimeterminalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.lastTimeTerminalNumber
     *
     * @param lasttimeterminalnumber the value for whexpenseresponse.lastTimeTerminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setLasttimeterminalnumber(String lasttimeterminalnumber) {
        this.lasttimeterminalnumber = lasttimeterminalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.lastTimeDate
     *
     * @return the value of whexpenseresponse.lastTimeDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getLasttimedate() {
        return lasttimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.lastTimeDate
     *
     * @param lasttimedate the value for whexpenseresponse.lastTimeDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setLasttimedate(String lasttimedate) {
        this.lasttimedate = lasttimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.tranMoney
     *
     * @return the value of whexpenseresponse.tranMoney
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTranmoney() {
        return tranmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.tranMoney
     *
     * @param tranmoney the value for whexpenseresponse.tranMoney
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTranmoney(String tranmoney) {
        this.tranmoney = tranmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.thisTimeBalance
     *
     * @return the value of whexpenseresponse.thisTimeBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getThistimebalance() {
        return thistimebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.thisTimeBalance
     *
     * @param thistimebalance the value for whexpenseresponse.thisTimeBalance
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setThistimebalance(String thistimebalance) {
        this.thistimebalance = thistimebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.tranType
     *
     * @return the value of whexpenseresponse.tranType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTrantype() {
        return trantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.tranType
     *
     * @param trantype the value for whexpenseresponse.tranType
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTrantype(String trantype) {
        this.trantype = trantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.thisTimeTerminalNumber
     *
     * @return the value of whexpenseresponse.thisTimeTerminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getThistimeterminalnumber() {
        return thistimeterminalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.thisTimeTerminalNumber
     *
     * @param thistimeterminalnumber the value for whexpenseresponse.thisTimeTerminalNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setThistimeterminalnumber(String thistimeterminalnumber) {
        this.thistimeterminalnumber = thistimeterminalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.thisTimeDate
     *
     * @return the value of whexpenseresponse.thisTimeDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getThistimedate() {
        return thistimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.thisTimeDate
     *
     * @param thistimedate the value for whexpenseresponse.thisTimeDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setThistimedate(String thistimedate) {
        this.thistimedate = thistimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.onlineTranCount
     *
     * @return the value of whexpenseresponse.onlineTranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getOnlinetrancount() {
        return onlinetrancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.onlineTranCount
     *
     * @param onlinetrancount the value for whexpenseresponse.onlineTranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOnlinetrancount(String onlinetrancount) {
        this.onlinetrancount = onlinetrancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.offlineTranCount
     *
     * @return the value of whexpenseresponse.offlineTranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getOfflinetrancount() {
        return offlinetrancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.offlineTranCount
     *
     * @param offlinetrancount the value for whexpenseresponse.offlineTranCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setOfflinetrancount(String offlinetrancount) {
        this.offlinetrancount = offlinetrancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.tranAuthenticationCode
     *
     * @return the value of whexpenseresponse.tranAuthenticationCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTranauthenticationcode() {
        return tranauthenticationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.tranAuthenticationCode
     *
     * @param tranauthenticationcode the value for whexpenseresponse.tranAuthenticationCode
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTranauthenticationcode(String tranauthenticationcode) {
        this.tranauthenticationcode = tranauthenticationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.testCardFlag
     *
     * @return the value of whexpenseresponse.testCardFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getTestcardflag() {
        return testcardflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.testCardFlag
     *
     * @param testcardflag the value for whexpenseresponse.testCardFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setTestcardflag(String testcardflag) {
        this.testcardflag = testcardflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.reservedField
     *
     * @return the value of whexpenseresponse.reservedField
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getReservedfield() {
        return reservedfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.reservedField
     *
     * @param reservedfield the value for whexpenseresponse.reservedField
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setReservedfield(String reservedfield) {
        this.reservedfield = reservedfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column whexpenseresponse.uploadFlag
     *
     * @return the value of whexpenseresponse.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getUploadflag() {
        return uploadflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column whexpenseresponse.uploadFlag
     *
     * @param uploadflag the value for whexpenseresponse.uploadFlag
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setUploadflag(String uploadflag) {
        this.uploadflag = uploadflag;
    }
}