package com.example.demo.model;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "y_daishousales")
public class YDaishousales {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.yNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer ynumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer znumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String accountdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.firstNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String firstnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.firstName
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.secondNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String secondnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.itemNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String itemnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.posCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer poscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_daishousales.posAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal posamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.id
     *
     * @return the value of y_daishousales.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.id
     *
     * @param id the value for y_daishousales.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.storeId
     *
     * @return the value of y_daishousales.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.storeId
     *
     * @param storeid the value for y_daishousales.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.posNo
     *
     * @return the value of y_daishousales.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.posNo
     *
     * @param posno the value for y_daishousales.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.yNumber
     *
     * @return the value of y_daishousales.yNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getYnumber() {
        return ynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.yNumber
     *
     * @param ynumber the value for y_daishousales.yNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setYnumber(Integer ynumber) {
        this.ynumber = ynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.zNumber
     *
     * @return the value of y_daishousales.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getZnumber() {
        return znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.zNumber
     *
     * @param znumber the value for y_daishousales.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setZnumber(Integer znumber) {
        this.znumber = znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.accountDate
     *
     * @return the value of y_daishousales.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getAccountdate() {
        return accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.accountDate
     *
     * @param accountdate the value for y_daishousales.accountDate
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setAccountdate(String accountdate) {
        this.accountdate = accountdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.firstNumber
     *
     * @return the value of y_daishousales.firstNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getFirstnumber() {
        return firstnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.firstNumber
     *
     * @param firstnumber the value for y_daishousales.firstNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setFirstnumber(String firstnumber) {
        this.firstnumber = firstnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.firstName
     *
     * @return the value of y_daishousales.firstName
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.firstName
     *
     * @param firstname the value for y_daishousales.firstName
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.secondNumber
     *
     * @return the value of y_daishousales.secondNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getSecondnumber() {
        return secondnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.secondNumber
     *
     * @param secondnumber the value for y_daishousales.secondNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setSecondnumber(String secondnumber) {
        this.secondnumber = secondnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.itemNumber
     *
     * @return the value of y_daishousales.itemNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getItemnumber() {
        return itemnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.itemNumber
     *
     * @param itemnumber the value for y_daishousales.itemNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setItemnumber(String itemnumber) {
        this.itemnumber = itemnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.posCount
     *
     * @return the value of y_daishousales.posCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPoscount() {
        return poscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.posCount
     *
     * @param poscount the value for y_daishousales.posCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPoscount(Integer poscount) {
        this.poscount = poscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_daishousales.posAmount
     *
     * @return the value of y_daishousales.posAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPosamount() {
        return posamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_daishousales.posAmount
     *
     * @param posamount the value for y_daishousales.posAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosamount(BigDecimal posamount) {
        this.posamount = posamount;
    }
}