package com.example.demo.model;

import java.math.BigDecimal;
import javax.persistence.*;

@Table(name = "ypayment")
public class Ypayment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer posno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer znumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.yNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer ynumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.payNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String payno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.payAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal payamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.payCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer paycount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.payCat
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private String paycat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private BigDecimal returnamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ypayment.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    private Integer returncount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.id
     *
     * @return the value of ypayment.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.id
     *
     * @param id the value for ypayment.id
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.storeId
     *
     * @return the value of ypayment.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.storeId
     *
     * @param storeid the value for ypayment.storeId
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setStoreid(String storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.posNo
     *
     * @return the value of ypayment.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPosno() {
        return posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.posNo
     *
     * @param posno the value for ypayment.posNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPosno(Integer posno) {
        this.posno = posno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.zNumber
     *
     * @return the value of ypayment.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getZnumber() {
        return znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.zNumber
     *
     * @param znumber the value for ypayment.zNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setZnumber(Integer znumber) {
        this.znumber = znumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.yNumber
     *
     * @return the value of ypayment.yNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getYnumber() {
        return ynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.yNumber
     *
     * @param ynumber the value for ypayment.yNumber
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setYnumber(Integer ynumber) {
        this.ynumber = ynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.payNo
     *
     * @return the value of ypayment.payNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPayno() {
        return payno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.payNo
     *
     * @param payno the value for ypayment.payNo
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayno(String payno) {
        this.payno = payno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.payAmount
     *
     * @return the value of ypayment.payAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.payAmount
     *
     * @param payamount the value for ypayment.payAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPayamount(BigDecimal payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.payCount
     *
     * @return the value of ypayment.payCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getPaycount() {
        return paycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.payCount
     *
     * @param paycount the value for ypayment.payCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPaycount(Integer paycount) {
        this.paycount = paycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.payCat
     *
     * @return the value of ypayment.payCat
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public String getPaycat() {
        return paycat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.payCat
     *
     * @param paycat the value for ypayment.payCat
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setPaycat(String paycat) {
        this.paycat = paycat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.returnAmount
     *
     * @return the value of ypayment.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public BigDecimal getReturnamount() {
        return returnamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.returnAmount
     *
     * @param returnamount the value for ypayment.returnAmount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setReturnamount(BigDecimal returnamount) {
        this.returnamount = returnamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ypayment.returnCount
     *
     * @return the value of ypayment.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public Integer getReturncount() {
        return returncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ypayment.returnCount
     *
     * @param returncount the value for ypayment.returnCount
     *
     * @mbg.generated Mon May 18 09:42:44 CST 2020
     */
    public void setReturncount(Integer returncount) {
        this.returncount = returncount;
    }
}